server:
  port: 8080
  tomcat:
    accesslog:
      enabled: true
      pattern: '%h %l %u %t "%r" %s %b %D'

spring:
  application:
    name: counter-api

  # Disable Spring Cloud AWS auto-configuration to avoid region issues
  autoconfigure:
    exclude:
      - io.awspring.cloud.autoconfigure.sqs.SqsAutoConfiguration
      - io.awspring.cloud.autoconfigure.core.AwsAutoConfiguration

  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/counterdb}
    username: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

  mvc:
    log-request-details: true
    log-resolved-exception: true

aws:
  sqs:
    endpoint: http://localhost:4566
    region: us-east-1
    queue-name: counter-increment-queue

sqs:
  queue-name: ${SQS_QUEUE_NAME:counter-increment-queue}
  endpoint: ${SQS_ENDPOINT:http://localhost:4566}
  region: ${SQS_REGION:us-east-1}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

logging:
  level:
    com.example.counter: INFO
    org.springframework.web: DEBUG
    org.springframework.web.servlet.DispatcherServlet: DEBUG
    org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG
    org.apache.http: DEBUG
    org.apache.http.wire: DEBUG
    org.springframework.boot.actuate.trace.http: DEBUG
    org.springframework.boot.web.servlet.FilterRegistrationBean: DEBUG
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"

---
spring:
  config:
    activate:
      on-profile: docker

  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://postgres:5432/counterdb}

logging:
  level:
    org.springframework.web: INFO
    org.springframework.web.servlet.DispatcherServlet: INFO
    org.springframework.web.filter.CommonsRequestLoggingFilter: INFO