server:
  port: 8080

spring:
  application:
    name: counter-api

  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/counterdb}
    username: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

logging:
  mvc:
    log-request-details: true
    log-resolved-exception: true
  config:
    activate:
      on-profile: docker

  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://postgres:5432/counterdb}

  level:
    org.springframework.web: INFO
    org.springframework.web.servlet.DispatcherServlet: INFO
    org.springframework.web.filter.CommonsRequestLoggingFilter: INFO
