doctrine_mongodb:
    connections:
        default:
            server: '%env(MONGODB_URL)%'
            options: {}
    default_database: events
    document_managers:
        default:
            auto_mapping: true
            mappings:
                App:
                    is_bundle: false
                    dir: '%kernel.project_dir%/src/Document'
                    prefix: 'App\Document'
                    alias: App
